# add for brume theme
auto: true
markdown: redcarpet
highlighter: null

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
# end
title:footstone
production_url : http://footstone.github.io
url: http://footstone.github.io
